project:
  type: website

website:
  title: "Yichen Wang"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
  

format:
  html:
    theme: cosmo
    css: styles.css
    # df-print: paged
    toc: false